#####  
# Define the source schemas for the conversion process.
import pandas as pd
import numpy as np
import datetime as dt

# DFKKOP schema
dfkkop_schema = {
    "Cont.Account": str,
    "BPartner": 'Int64',
    "Contract": str,
    "G/L acct": str,
    "MTrans": str,
    "STrans": str,
    "Amount": float, 
    "Crcy": str,
    "Doc. No.": str,
    "CoCd": str,
    "Status": str,
    "Pstng Date": pd.Timestamp,
    "Due": pd.Timestamp,
    "Doc. Date": pd.Timestamp,
    "Tax Port.": float,
    "Clear. doc": str,
    "DT": str
}

# EVER schema
ever_schema = {
    "Cl. Contract": str,
    "CoCd": str,
    "Dv": str,
    "P/C": str,
    "AD": str,
    "Alt.port.": str,
    "BD": str,
    "OvdgBBC": str,
    "NA": str,
    "JI": str,
    "BM": str,
    "BBR": str,
    "RBR": str,
    "PS": str,
    "Cost Ctr": str,
    "Text for contract": str,
    "Cont.start": pd.Timestamp,
    "Leg. MID": pd.Timestamp,
    "Cont. end": pd.Timestamp,
    "Canc.date": pd.Timestamp,
    "NCU": str,
    "CU": str,
    "Renew.date": pd.Timestamp,
    "NRU": str,
    "RU": str,
    "Ut.concl.": str,
    "CustConcl.": str,
    "Time cust.": str,
    "Pers.No.": str,
    "Contr.from leg.syst.": str,
    "Created On": pd.Timestamp,
    "Created By": str,
    "Chngd on": pd.Timestamp,
    "Changed By": str,
    "AGrp": str,
    "DlI": str,
    "Tax Jur.": str,
    "MOS": str,
    "Inv. Order": str,
    "WBS Element": str,
    "Profit Ctr": str,
    "A": str,
    "OutChkGrp": str,
    "No. outsortings": 'Int64',
    "PPtype": str,
    "StM": str,
    "BusA": str,
    "Segment": str,
    "Serv.Prov.": str,
    "Reference no. service provider": str,
    "BM": str,
    "StGp": str,
    "AltSM": str,
    "BlTer": str,
    "BFamt": float,
    "BFamt": float,
    "Employee": str,
    "SP": str,
    "Document": str,
    "PS StDate": pd.Timestamp,
    "Payment Class": str,
    "InvServPro": str,
    "COact.asgn": str,
    "BP": str,
    "CoCls": str,
    "Re": str,
    "CGrp": str,
    "BEx": str,
    "PP": str,
    "OSB Group": str,
    "C": str,
    "Rule group": str,
    "RegStGrp.": str,
    "Master Data Grp": str,
    "Collection Strategy": str,
    "Contact Person": str,
    "Installat.": str,
    "Cont.Account": str,
    "SMI": str,
    "SMO": str,
    "AO": str,
    "M/I Date": pd.Timestamp,
    "M/O Date": pd.Timestamp,
    "Stop date": pd.Timestamp,
    "JFB": str,
    "DP": str,
    "MDP": str,
    "DLR": str,
    "P": str,
    "TC": str,
    "RCC": str,
    "LC": str,
    "Contract class": str,
    "Owner of the premise": str,
    "Installation shut down option": str,
    "Owner move out": str,
    "Contract class": str
}


# ZDM_PREMDETAILS schema
prem_schema = {
    "MRU": str, 
    "Con. Object": str,
    "Premise": str,
    "Installation": str,
    "Rate Category": str,
    "Device Location": str,
    "Location": str,
    "Business Partener": 'Int64',
    "Customer Name": str,
    "Contract Account": str,
    "Leg.Contract Account": str,
    "CA ADID": str,
    "EBill": str,
    "Contract": str,
    "ADID": str,
    "Phone Number": str,
    "Manufacturer": str,
    "Material": str,
    "Serial Number": str,
    "instal Date": pd.Timestamp,
    "Construction Year": 'Int64',
    "Meter Size": str,
    "Pressure Factor": float,
    "ERT Material": str,
    "ERT Serial Number": str,
    "ERT instal Date": pd.Timestamp,
    "Service Address": str,
    "Zip Code": str,
    "Premise type": str,
    "Tax Jursidiction": str
}



